### ISSUE TITLE
transient detection - rec threshold

### ISSUE THREAD

**Issue by 2roundrobins** [2roundrobins/messiaen#10]
can we make it beat/transient detected (is it possible on norns?)
so it takes audio starting only from when the treshold is reached (threshold?) - like in CC2 or MLRE
and it takes that material and uses it as a starting point - maybe just a RECORDING THRESHOLD

so the birds always sample on the the start of the transient note

**Comment by sonocircuit** [comment]
this has been addressed so we can close the issue.
