### ISSUE TITLE
mood param and UI additions

### ISSUE THREAD

**Issue by sonocircuit** [2roundrobins/messiaen#13]
I played around with `bird_loop_size` and found that the timbre changes nicely with size. at lower values (0.05s) the bird call sounds more nervous/aggressive and at higher values (1s) smoother/calmer. I added the param `mood` which changes the `bird_loop_size`. have a play and let me know what you think.

also. as there is no pos encoder anymore we can populate it with something else. I thought it would be nice to surface 4 parameter to the main page: ENC2 mood, ENC3 level. While holding K1: ENC2 position (pan), ENC3 distance (cutoff). we can have a look during our next session.

**Comment by 2roundrobins** [comment]
now added `distance` as `area:` on the main screen. feel that this might be the best option to quickly shape the sound. once you boot it up. will have to fine tune the `mood` to to get it just right. 

definitely it would be a cool idea to combo key it to bird shape the bird voice.
