### ISSUE TITLE
panning (bipolar)

### ISSUE THREAD

**Issue by 2roundrobins** [2roundrobins/messiaen#23]
the position parameter could benefit from using the bipolar_as_pan_widget formatter, rather than a flat -1 to 1 controlspec. you can add this by:
invoking frm = require 'formatters' among your includes/requires
swapping the current parameter for params:add_control(bird_params[i].."_pan", "position", controlspec.new(-1, 1, 'lin', 0, 0, ""), frm.bipolar_as_pan_widget)

**Comment by sonocircuit** [comment]
added my own widget... if you prefer the bipolar pan thingy feel free to change.
