### ISSUE TITLE
lfo idea

### ISSUE THREAD

**Issue by 2roundrobins** [2roundrobins/messiaen#24]
in the update (flight option)

**Comment by sonocircuit** [comment]
in garden mode there is a params called `bird activity` (0-100%) which is only visible if `bird position` is set to `auto`. this is meant to be a one knob macro that will control the depth and rate of several lfos controlling pan and distance of the birds.

TODO: add the LFOs and experiment with parameters and scaling.

**Comment by sonocircuit** [comment]
the latest version includes a move_birds() function to simulate bird movement.
