### ISSUE TITLE
garden mode! + populate function

### ISSUE THREAD

**Issue by 2roundrobins** [2roundrobins/messiaen#5]
GARDEN mode

entering this mode should create a whole new environment. currently I'm thinking like this;

- in params menu or by pressing K1+K3 you can toggle garden
- when garden is on the recorded material is distributed through softcut 1 to 5
-  in params you can choose which bird is currently in your garden
- each softcut playhead is panned a bit differently, creating a wider image
- each playhead is filtered a bit, creating depth
- the birds randomly play their song in a timely manner, creating a garden effect
- sc 6 stays file load for atmosphere

**Comment by sonocircuit** [comment]
let's look into this next. I think the best approach would be to simply add birds 2-4 (visitors 1-3) when garden mode is activated.

**Comment by 2roundrobins** [comment]
yep, still we get rogue birds chirping about.

**Comment by 2roundrobins** [comment]
also garden mode ideas for encoder control:

ENC: 1 separation (the pauses between bird songs)
ENC: 2 spread (panning)
ENC 3: master volume
